"""Add timestamps

Revision ID: 84dbe6ca4d2f
Revises: 
Create Date: 2025-04-11 20:38:32.697978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dbe6ca4d2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
